### ISSUE TITLE
Mostrar solo las unidades Organizativas asigandas al usuario

### ISSUE THREAD

**Issue by HelderCastrillon** [EyeSeeTea/msf_apps#14]
Se realizó el desarrollo para presentar solo las unidades organizativas asignadas al usuario. SIn embargo, fue necesario hacer consultas a la API dentro de un forEach lo que ocasiona demora al cargar inicialmente el arbol por los CallBack que quedan en espera. la Solución que propongo es poner  un "Loading, please wait" que oculte el arbol hasta que este totalmente cargado.
en la semana termino el desarrollo

**Comment by josemp10** [comment]
¿Cómo va esto? ¿Has podido avanzar algo?

**Comment by HelderCastrillon** [comment]
ya carga las unidades de asigandas al usuario per

**Comment by HelderCastrillon** [comment]
Hola Jose,
Ya quedó listo lo del arbol de Unidades organizativas, hay que tener en cuenta que siempre hay que asignarle unidades organizativas a los usuarios, porque hay ocasiones que se crea un Superuser y a este no se asigna unidades y la api "api/me" no trae ninguna unidad y como consecuencia no carga el árbol. Traté de utilizar la api "api/User" pero curiosamente no trae todos los usuarios  ni siquiera el mismo que se ingresó. "es por permisos", pero si eres Superusuario si trae todo.

Les pido probar y confirmar si quedo bien. @josemp10, @vgarciabnz, @markodavid
